### ISSUE TITLE
Suggestion: add reset for one shot use

### ISSUE THREAD

**Issue by custeve** [stevemarple/AsyncDelay#1]
I'll probably do this myself, but thought I'd post the suggestion. It'd be nice if the ifExpired function returns FALSE if the object is not yet started or has been reset. The application for this would be single shot operations instead of repeat operations. The use would be to include the call to reset the object (using a reset() or stop() function) in the call to ifExpired.

**Comment by stevemarple** [comment]
There is no variable which records whether a timer has been started or not. I believe it is unnecessary for most use cases and I don't want to increase the memory footprint by adding a variable which in general is not required. In any event a user can identify if a timer has been started or not without adding extra variables (either internal or external to the library). 

When a timer is created with the default constructor like so
````
AsyncDelay timer;
````
and started with 
````
timer.start(5000, AsyncDelay::MILLIS);
````
then delay is initialized as zero, `getDelay()` will only return 5000 after the call to `start()`.
