### ISSUE TITLE
Timer not restart after .repeat () function

### ISSUE THREAD

**Issue by DarkBeardRUS** [stevemarple/AsyncDelay#2]
The .repeat () function does not restart the timer, but only sets the flag that it is not isExpired. And if the timer, for example, out of 30 seconds has passed 29, then after .repeat () the timer will become isExpired in 1 second.

**Comment by stevemarple** [comment]
What you have described is intended. See [AsyncDelay.h](https://github.com/stevemarple/AsyncDelay/blob/master/src/AsyncDelay.h#L67):

```
// Restart the delay from when it expired (not now).
inline void repeat(void) 
```
For applications that perform data sampling this is probably the desired behaviour, so that sampling occurs as regularly as possible. Perhaps you want `restart()` ?

```
// Restart the delay from now.
inline void restart(void)
```
