### ISSUE TITLE
How do I stop a timer?

### ISSUE THREAD

**Issue by SteveRMann** [stevemarple/AsyncDelay#4]
How do I stop a timer?

For example, to flash an LED with a 5-second on then a one-second off period:
![Async-1](https://user-images.githubusercontent.com/8091425/124861929-78c74580-df82-11eb-9cd5-9fb45ccffb58.jpg)

My flow is to start the ON timer.
Turn on the LED
When the ON timer expires, 
Turn off the LED
STOP the ON timer
Start the OFF timer
When the OFF timer expires,
Turn ON the LED
STOP the OFF timer
Start the ON timer

repeat

**Comment by stevemarple** [comment]
There is no need to stop a timer, it continuing and expiring later doesn't do anything (there is no callback that would make an action happen). There is an `expire() ` function that can force a timer to be expired but that isn't needed in your flow as you wait for it to be expired anyway.

**Comment by SteveRMann** [comment]
I disagree. If the OFF timer is not stopped, then the LED is always on because the OFF timer expires during the ON time.
I have a better idea- how would you code this to get a 5-sec. on, 1-sec off period?

**Comment by stevemarple** [comment]
The underlying timer used by `AsyncDelay` is the system timer that is user for `millis()` and other important functions. Stopping it isn't an option. Presumably you have one `AsyncDelay` object used for the ON period and another for the OFF period? You can probably arrange that which one you consider depending on the current ON or OFF state. `AsyncDelay`will do what you need, you just need to arrange your state machine appropriately.

**Comment by SteveRMann** [comment]
As I said, I am evaluating seven libraries from the Arduino Library Manager.  AsyncDelay and AsyncTimer are the only ones that don't have a stop method.  I can accomplish my test pattern by using a state, but that complicates the code that the library was supposed to simplify.

I will send you my summary including test code when I am finished.
